# Generated by Django 5.2.9 on 2026-01-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('adresse', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Cursus',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=32)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tlf', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('amis', models.ManyToManyField(blank=True, to='ump_app.person')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ump_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ump_app.person')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ump_app.person')),
                ('office', models.CharField(max_length=32)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ump_app.campus')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ump_app.job')),
            ],
            bases=('ump_app.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ump_app.person')),
                ('annee', models.IntegerField()),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ump_app.cursus')),
            ],
            bases=('ump_app.person',),
        ),
    ]
